"""empty message

Revision ID: 3a60041056d3
Revises: 8011a945b434
Create Date: 2021-08-17 23:06:18.468697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a60041056d3'
down_revision = '8011a945b434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_category_name_category'), 'category', ['category_name'], ['name'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_category_name_category'), type_='foreignkey')
        batch_op.drop_column('category_name')

    op.drop_table('category')
    # ### end Alembic commands ###
